create table cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint, primary key (id)) engine=MyISAM;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=MyISAM;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=MyISAM;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=MyISAM;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=MyISAM;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=MyISAM;
create table item_pedido (id bigint not null auto_increment, observacao varchar(255), preco_total decimal(38,2), preco_unitario decimal(38,2), quantidade integer, pedido_id bigint not null, produto_id bigint not null, primary key (id)) engine=MyISAM;
create table pedido (id bigint not null auto_increment, data_cancelamento datetime, data_confirmacao datetime, data_criacao datetime not null, data_entrega datetime, endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), status smallint, sub_total decimal(38,2) not null, taxa_frete decimal(38,2) not null, valor_total decimal(38,2) not null, usuario_cliente_id bigint not null, endereco_cidade_id bigint, forma_pagamento_id bigint not null, restaurante_id bigint not null, primary key (id)) engine=MyISAM;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=MyISAM;
create table produto (id bigint not null auto_increment, ativo bit not null, nome varchar(255) not null, preco decimal(38,2) not null, restaurante_id bigint not null, primary key (id)) engine=MyISAM;
create table restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), taxa_frete decimal(38,2), cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=MyISAM;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=MyISAM;
create table usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=MyISAM;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=MyISAM;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table item_pedido add constraint FK60ym08cfoysa17wrn1swyiuda foreign key (pedido_id) references pedido (id);
alter table item_pedido add constraint FKtk55mn6d6bvl5h0no5uagi3sf foreign key (produto_id) references produto (id);
alter table pedido add constraint FKcccmjvm9ytuxbe00h3wmtm77y foreign key (usuario_cliente_id) references usuario (id);
alter table pedido add constraint FKk987vfg9cpgx7qxj3166fdqig foreign key (endereco_cidade_id) references cidade (id);
alter table pedido add constraint FKqaa411xsl0xu4tkvt1wpccd3b foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table pedido add constraint FK3eud5cqmgsnltyk704hu3qj71 foreign key (restaurante_id) references restaurante (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
insert into cozinha (nome) values ('Tailandesa');
insert into cozinha (nome) values ('Japonesa');
insert into cozinha (nome) values ('Indiana');
insert into estado (nome) values ('Minas Gerais');
insert into estado (nome) values ('São Paulo');
insert into estado (nome) values ('Rio de Janeiro');
insert into estado (nome) values ('Distrito Federal');
insert into cidade (nome, estado_id) values ('Brasilia', 4);
insert into cidade (nome, estado_id) values ('Niterói', 3);
insert into cidade (nome, estado_id) values ('Uberlândia', 1);
insert into cidade (nome, estado_id) values ('Araguari', 1);
insert into cidade (nome, estado_id) values ('Campinas', 2);
insert into restaurante (nome, taxa_frete, cozinha_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_cidade_id, data_cadastro, data_atualizacao) values ('Aconchego Mineiro', 10.0, 1, '38.408-294', 'Rua Patrulheiro OSmar Tavares', '1682', 'apto 202', 3, '2023-04-12 14.07.00', '2023-04-12 14.07.00');
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Bom Apetite', 12.0, 2, '2023-04-12 14.07.00', '2023-04-12 14.07.00');
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Tuk Tuk', 0, 3, '2023-04-12 14.07.00', '2023-04-12 14.07.00');
insert into produto (nome, preco, ativo, restaurante_id) values ('Macchiato', 7.9, true, 1);
insert into produto (nome, preco, ativo, restaurante_id) values ('Cappucino', 6.9, true, 1);
insert into produto (nome, preco, ativo, restaurante_id) values ('Frango com curry', 26, true, 3);
insert into produto (nome, preco, ativo, restaurante_id) values ('Arroz grego', 12.9, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Churrasco', 35.8, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Lasanha', 23, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Mexidão', 16.7, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Expresso duplo', 4.5, true, 1);
insert into forma_pagamento (descricao) values ('À Vista Crédito');
insert into forma_pagamento (descricao) values ('PIX');
insert into forma_pagamento (descricao) values ('Parcelado Crédito');
insert into forma_pagamento (descricao) values ('Cartão Débito');
insert into permissao (nome, descricao) values ('Admin', 'Permissão de Administrador');
insert into permissao (nome, descricao) values ('Colaborador', 'Permissão de Colaborador');
insert into Grupo (nome) values ('Gerente');
insert into Grupo (nome) values ('Cozinheiro');
insert into Grupo (nome) values ('Financeiro');
insert into usuario (nome, email, senha, data_cadastro) values ('Adams Zago', 'awzago@gmail.com', '123', '2023-04-17 14.07.00');
insert into usuario (nome, email, senha, data_cadastro) values ('Jesebel Caixeta', 'jesebelfisio@gmail.com', '456', '2023-04-17 14.07.00');
insert into usuario (nome, email, senha, data_Cadastro) values ('Davi Ribeiro Zago', 'davirz@hotmail.com', '789', '2023-04-17 14.07.00');
insert into grupo_permissao(grupo_id, permissao_id) values (1,1), (2,2), (3,2);
insert into usuario_grupo(usuario_id, grupo_id) values (1,1), (2,3), (3,2);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 1), (3, 3);
create table cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint, primary key (id)) engine=MyISAM;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=MyISAM;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=MyISAM;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=MyISAM;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=MyISAM;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=MyISAM;
create table item_pedido (id bigint not null auto_increment, observacao varchar(255), preco_total decimal(38,2), preco_unitario decimal(38,2), quantidade integer, pedido_id bigint not null, produto_id bigint not null, primary key (id)) engine=MyISAM;
create table pedido (id bigint not null auto_increment, data_cancelamento datetime, data_confirmacao datetime, data_criacao datetime not null, data_entrega datetime, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), status smallint, sub_total decimal(38,2) not null, taxa_frete decimal(38,2) not null, valor_total decimal(38,2) not null, usuario_cliente_id bigint not null, endereco_cidade_id bigint, forma_pagamento_id bigint not null, restaurante_id bigint not null, primary key (id)) engine=MyISAM;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=MyISAM;
create table produto (id bigint not null auto_increment, ativo bit not null, nome varchar(255) not null, preco decimal(38,2) not null, restaurante_id bigint not null, primary key (id)) engine=MyISAM;
create table restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), taxa_frete decimal(38,2), cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=MyISAM;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=MyISAM;
create table usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=MyISAM;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=MyISAM;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table item_pedido add constraint FK60ym08cfoysa17wrn1swyiuda foreign key (pedido_id) references pedido (id);
alter table item_pedido add constraint FKtk55mn6d6bvl5h0no5uagi3sf foreign key (produto_id) references produto (id);
alter table pedido add constraint FKcccmjvm9ytuxbe00h3wmtm77y foreign key (usuario_cliente_id) references usuario (id);
alter table pedido add constraint FKk987vfg9cpgx7qxj3166fdqig foreign key (endereco_cidade_id) references cidade (id);
alter table pedido add constraint FKqaa411xsl0xu4tkvt1wpccd3b foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table pedido add constraint FK3eud5cqmgsnltyk704hu3qj71 foreign key (restaurante_id) references restaurante (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
insert into cozinha (nome) values ('Tailandesa');
insert into cozinha (nome) values ('Japonesa');
insert into cozinha (nome) values ('Indiana');
insert into estado (nome) values ('Minas Gerais');
insert into estado (nome) values ('São Paulo');
insert into estado (nome) values ('Rio de Janeiro');
insert into estado (nome) values ('Distrito Federal');
insert into cidade (nome, estado_id) values ('Brasilia', 4);
insert into cidade (nome, estado_id) values ('Niterói', 3);
insert into cidade (nome, estado_id) values ('Uberlândia', 1);
insert into cidade (nome, estado_id) values ('Araguari', 1);
insert into cidade (nome, estado_id) values ('Campinas', 2);
insert into restaurante (nome, taxa_frete, cozinha_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_cidade_id, data_cadastro, data_atualizacao) values ('Aconchego Mineiro', 10.0, 1, '38.408-294', 'Rua Patrulheiro OSmar Tavares', '1682', 'apto 202', 3, '2023-04-12 14.07.00', '2023-04-12 14.07.00');
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Bom Apetite', 12.0, 2, '2023-04-12 14.07.00', '2023-04-12 14.07.00');
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Tuk Tuk', 0, 3, '2023-04-12 14.07.00', '2023-04-12 14.07.00');
insert into produto (nome, preco, ativo, restaurante_id) values ('Macchiato', 7.9, true, 1);
insert into produto (nome, preco, ativo, restaurante_id) values ('Cappucino', 6.9, true, 1);
insert into produto (nome, preco, ativo, restaurante_id) values ('Frango com curry', 26, true, 3);
insert into produto (nome, preco, ativo, restaurante_id) values ('Arroz grego', 12.9, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Churrasco', 35.8, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Lasanha', 23, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Mexidão', 16.7, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Expresso duplo', 4.5, true, 1);
insert into forma_pagamento (descricao) values ('À Vista Crédito');
insert into forma_pagamento (descricao) values ('PIX');
insert into forma_pagamento (descricao) values ('Parcelado Crédito');
insert into forma_pagamento (descricao) values ('Cartão Débito');
insert into permissao (nome, descricao) values ('Admin', 'Permissão de Administrador');
insert into permissao (nome, descricao) values ('Colaborador', 'Permissão de Colaborador');
insert into Grupo (nome) values ('Gerente');
insert into Grupo (nome) values ('Cozinheiro');
insert into Grupo (nome) values ('Financeiro');
insert into usuario (nome, email, senha, data_cadastro) values ('Adams Zago', 'awzago@gmail.com', '123', '2023-04-17 14.07.00');
insert into usuario (nome, email, senha, data_cadastro) values ('Jesebel Caixeta', 'jesebelfisio@gmail.com', '456', '2023-04-17 14.07.00');
insert into usuario (nome, email, senha, data_Cadastro) values ('Davi Ribeiro Zago', 'davirz@hotmail.com', '789', '2023-04-17 14.07.00');
insert into grupo_permissao(grupo_id, permissao_id) values (1,1), (2,2), (3,2);
insert into usuario_grupo(usuario_id, grupo_id) values (1,1), (2,3), (3,2);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 1), (3, 3);
create table cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint, primary key (id)) engine=MyISAM;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=MyISAM;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=MyISAM;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=MyISAM;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=MyISAM;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=MyISAM;
create table item_pedido (id bigint not null auto_increment, observacao varchar(255), preco_total decimal(38,2), preco_unitario decimal(38,2), quantidade integer, pedido_id bigint not null, produto_id bigint not null, primary key (id)) engine=MyISAM;
create table pedido (id bigint not null auto_increment, data_cancelamento datetime, data_confirmacao datetime, data_criacao datetime not null, data_entrega datetime, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), status smallint, sub_total decimal(38,2) not null, taxa_frete decimal(38,2) not null, valor_total decimal(38,2) not null, usuario_cliente_id bigint not null, endereco_cidade_id bigint, forma_pagamento_id bigint not null, restaurante_id bigint not null, primary key (id)) engine=MyISAM;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=MyISAM;
create table produto (id bigint not null auto_increment, ativo bit not null, nome varchar(255) not null, preco decimal(38,2) not null, restaurante_id bigint not null, primary key (id)) engine=MyISAM;
create table restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), taxa_frete decimal(38,2), cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=MyISAM;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=MyISAM;
create table usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=MyISAM;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=MyISAM;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table item_pedido add constraint FK60ym08cfoysa17wrn1swyiuda foreign key (pedido_id) references pedido (id);
alter table item_pedido add constraint FKtk55mn6d6bvl5h0no5uagi3sf foreign key (produto_id) references produto (id);
alter table pedido add constraint FKcccmjvm9ytuxbe00h3wmtm77y foreign key (usuario_cliente_id) references usuario (id);
alter table pedido add constraint FKk987vfg9cpgx7qxj3166fdqig foreign key (endereco_cidade_id) references cidade (id);
alter table pedido add constraint FKqaa411xsl0xu4tkvt1wpccd3b foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table pedido add constraint FK3eud5cqmgsnltyk704hu3qj71 foreign key (restaurante_id) references restaurante (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
insert into cozinha (nome) values ('Tailandesa');
insert into cozinha (nome) values ('Japonesa');
insert into cozinha (nome) values ('Indiana');
insert into estado (nome) values ('Minas Gerais');
insert into estado (nome) values ('São Paulo');
insert into estado (nome) values ('Rio de Janeiro');
insert into estado (nome) values ('Distrito Federal');
insert into cidade (nome, estado_id) values ('Brasilia', 4);
insert into cidade (nome, estado_id) values ('Niterói', 3);
insert into cidade (nome, estado_id) values ('Uberlândia', 1);
insert into cidade (nome, estado_id) values ('Araguari', 1);
insert into cidade (nome, estado_id) values ('Campinas', 2);
insert into restaurante (nome, taxa_frete, cozinha_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_cidade_id, data_cadastro, data_atualizacao) values ('Aconchego Mineiro', 10.0, 1, '38.408-294', 'Rua Patrulheiro OSmar Tavares', '1682', 'apto 202', 3, '2023-04-12 14.07.00', '2023-04-12 14.07.00');
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Bom Apetite', 12.0, 2, '2023-04-12 14.07.00', '2023-04-12 14.07.00');
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Tuk Tuk', 0, 3, '2023-04-12 14.07.00', '2023-04-12 14.07.00');
insert into produto (nome, preco, ativo, restaurante_id) values ('Macchiato', 7.9, true, 1);
insert into produto (nome, preco, ativo, restaurante_id) values ('Cappucino', 6.9, true, 1);
insert into produto (nome, preco, ativo, restaurante_id) values ('Frango com curry', 26, true, 3);
insert into produto (nome, preco, ativo, restaurante_id) values ('Arroz grego', 12.9, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Churrasco', 35.8, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Lasanha', 23, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Mexidão', 16.7, true, 2);
insert into produto (nome, preco, ativo, restaurante_id) values ('Expresso duplo', 4.5, true, 1);
insert into forma_pagamento (descricao) values ('À Vista Crédito');
insert into forma_pagamento (descricao) values ('PIX');
insert into forma_pagamento (descricao) values ('Parcelado Crédito');
insert into forma_pagamento (descricao) values ('Cartão Débito');
insert into permissao (nome, descricao) values ('Admin', 'Permissão de Administrador');
insert into permissao (nome, descricao) values ('Colaborador', 'Permissão de Colaborador');
insert into Grupo (nome) values ('Gerente');
insert into Grupo (nome) values ('Cozinheiro');
insert into Grupo (nome) values ('Financeiro');
insert into usuario (nome, email, senha, data_cadastro) values ('Adams Zago', 'awzago@gmail.com', '123', '2023-04-17 14.07.00');
insert into usuario (nome, email, senha, data_cadastro) values ('Jesebel Caixeta', 'jesebelfisio@gmail.com', '456', '2023-04-17 14.07.00');
insert into usuario (nome, email, senha, data_Cadastro) values ('Davi Ribeiro Zago', 'davirz@hotmail.com', '789', '2023-04-17 14.07.00');
insert into grupo_permissao(grupo_id, permissao_id) values (1,1), (2,2), (3,2);
insert into usuario_grupo(usuario_id, grupo_id) values (1,1), (2,3), (3,2);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 1), (3, 3);
